steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['install']
- name: 'node'
  entrypoint: 'npm'
  args: ['test']
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t europe-west1-docker.pkg.dev/$PROJECT_ID/synapps-sandbox-registry/quickstart:$TAG_NAME .
  automapSubstitutions: true
- name: 'gcr.io/cloud-builders/helm'
  args:
  - 'upgrade'
  - '--install'
  - 'pocketmailer'
  - './helm'
  - '--namespace'
  - 'mailer'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west9'
  - 'CLOUDSDK_CONTAINER_CLUSTER=gke-sandbox'
images:
- 'europe-west1-docker.pkg.dev/$PROJECT_ID/synapps-sandbox-registry/quickstart:$TAG_NAME'
options:
  logging: CLOUD_LOGGING_ONLY